$("#front_lock_placeholder").append(function(){
    return '<div class="card card_element"><div class="card-header">Front door</div><div class="card-body"><div class="btn-group" role="group" aria-label="Front_Lock"><input type="radio" class="btn-check" name="Front_Lock" id="front_lock"  autocomplete="off" checked><label class="btn btn-outline-success" for="front_lock">Lock</label><input type="radio" class="btn-check" name="Front_Lock" id="front_unlock" autocomplete="off"><label class="btn btn-outline-danger" for="front_unlock">Unlock</label></div></div></div>'
});
$("#bedroom_lock_placeholder").append(function(){
    return '<div class="card card_element"> <div class="card-header"> Master Bedroom </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="M_Bedroom_Lock"> <input type="radio" class="btn-check" name="M_Bedroom_Lock" id="M_Bedroom_Lock" autocomplete="off" checked> <label class="btn btn-outline-success" for="M_Bedroom_Lock">Lock</label> <input type="radio" class="btn-check" name="M_Bedroom_Lock" id="M_Bedroom_unLock" autocomplete="off"> <label class="btn btn-outline-danger" for="M_Bedroom_unLock">Unlock</label> </div> </div> </div>'
});
$("#cameras_placeholder").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen </div> <div class="card-body"> place for video camera </div> </div> <div class="card card_element col-5 col-lg-3"> <div class="card-header"> Corridor </div> <div class="card-body"> place for video camera </div> </div> <div class="card card_element col-5 col-lg-3"> <div class="card-header"> Home Office </div> <div class="card-body"> place for video camera </div> </div> <div class="card card_element col-5 col-lg-3"> <div class="card-header"> Master Bedroom </div> <div class="card-body"> place for video camera </div> </div>'
})
$("#bedroom_light_1").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Master Bedroom Main Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Master_Bedroom_Main_Light"> <input type="radio" class="btn-check" name="Master_Bedroom_Main_Light" id="Master_Bedroom_Main_Light_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Master_Bedroom_Main_Light_ON">ON</label> <input type="radio" class="btn-check" name="Master_Bedroom_Main_Light" id="Master_Bedroom_Main_Light_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Master_Bedroom_Main_Light_OFF">OFF</label> </div> </div> </div>'
});
$("#bedroom_light_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Master Bedroom Ambient Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Master_Bedroom_Ambient_Light"> <input type="radio" class="btn-check" name="Master_Bedroom_Ambient_Light" id="Master_Bedroom_Ambient_Light_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Master_Bedroom_Ambient_Light_ON">ON</label> <input type="radio" class="btn-check" name="Master_Bedroom_Ambient_Light" id="Master_Bedroom_Ambient_Light_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Master_Bedroom_Ambient_Light_OFF">OFF</label> </div> </div> </div>'
});
$("#office_light_1").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Office Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="office_Main_Light_System"> <input type="radio" class="btn-check" name="office_Main_Light_System" id="office_Main_Light_System_on"autocomplete="off" checked> <label class="btn btn-outline-success" for="office_Main_Light_System_on">ON</label> <input type="radio" class="btn-check" name="office_Main_Light_System" id="office_Main_Light_System_off" autocomplete="off"> <label class="btn btn-outline-danger" for="office_Main_Light_System_off">OFF</label> </div> </div> </div>'
});
$("#office_light_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Office Ambient Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="office_Ambient_Light_System"> <input type="radio" class="btn-check" name="office_Ambient_Light_System" id="office_Ambient_Light_System_on"autocomplete="off" checked> <label class="btn btn-outline-success" for="office_Ambient_Light_System_on">ON</label> <input type="radio" class="btn-check" name="office_Ambient_Light_System" id="office_Ambient_Light_System_off" autocomplete="off"> <label class="btn btn-outline-danger" for="office_Ambient_Light_System_off">OFF</label> </div> </div> </div>'
});
$("#kitchen_light_1").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen Main Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Kitchen_Main_Light2"> <input type="radio" class="btn-check" name="Kitchen_Main_Light2" id="Kitchen_Main_Light2_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Kitchen_Main_Light2_ON">ON</label> <input type="radio" class="btn-check" name="Kitchen_Main_Light2" id="Kitchen_Main_Light2_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Kitchen_Main_Light2_OFF">OFF</label> </div> </div> </div>'
});
$("#kitchen_light_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen Ambient Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Kitchen_Ambient_Light2"> <input type="radio" class="btn-check" name="Kitchen_Ambient_Light2" id="Kitchen_Ambient_Light2_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Kitchen_Ambient_Light2_ON">ON</label> <input type="radio" class="btn-check" name="Kitchen_Ambient_Light2" id="Kitchen_Ambient_Light2_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Kitchen_Ambient_Light2_OFF">OFF</label> </div> </div> </div>'
});
$("#bathroom_light").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Bathroom Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="BathroomLight"> <input type="radio" class="btn-check" name="BathroomLight" id="BathroomLight_ON"  autocomplete="off" checked> <label class="btn btn-outline-success" for="BathroomLight_ON">ON</label> <input type="radio" class="btn-check" name="BathroomLight" id="BathroomLight_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="BathroomLight_OFF">OFF</label> </div> </div> </div>'
});
$("#corridor_light_1").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Corridor Main Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Corridor_light_main2"> <input type="radio" class="btn-check" name="Corridor_light_main2" id="Corridor_light_main2_on"  autocomplete="off" checked> <label class="btn btn-outline-success" for="Corridor_light_main2_on">ON</label> <input type="radio" class="btn-check" name="Corridor_light_main2" id="Corridor_light_main2_off" autocomplete="off"> <label class="btn btn-outline-danger" for="Corridor_light_main2_off">OFF</label> </div> </div> </div>'
});
$("#corridor_light_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Corridor Ambient Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Corridor_light_Ambient2"> <input type="radio" class="btn-check" name="Corridor_light_Ambient2" id="Corridor_light_Ambient2_on"  autocomplete="off" checked> <label class="btn btn-outline-success" for="Corridor_light_Ambient2_on">ON</label> <input type="radio" class="btn-check" name="Corridor_light_Ambient2" id="Corridor_light_Ambient2_off" autocomplete="off"> <label class="btn btn-outline-danger" for="Corridor_light_Ambient2_off">OFF</label> </div> </div> </div>'
});
$("#bedroom_blinds").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Master Bedroom Blinds </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Master_Bedroom_Window_blinds"> <input type="radio" class="btn-check" name="Master_Bedroom_Window_blinds" id="Master_blinds_Open"autocomplete="off" checked> <label class="btn btn-outline-success" for="Master_blinds_Open">Open</label> <input type="radio" class="btn-check" name="Master_Bedroom_Window_blinds" id="Master_blinds_Closed" autocomplete="off"> <label class="btn btn-outline-danger" for="Master_blinds_Closed">Close</label> </div> </div> </div>'
});
$("#office_blinds").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Office Blinds </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Office_blinds"> <input type="radio" class="btn-check" name="Office_blinds" id="Office_blinds_Open"autocomplete="off" checked> <label class="btn btn-outline-success" for="Office_blinds_Open">Open</label> <input type="radio" class="btn-check" name="Office_blinds" id="Office_blinds_Closed" autocomplete="off"> <label class="btn btn-outline-danger" for="Office_blinds_Closed">Close</label> </div> </div> </div>'
});
$("#kitchen_blinds").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Kitchen Blinds </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Kitchen_blinds"> <input type="radio" class="btn-check" name="Kitchen_blinds" id="Kitchen_blinds_Open"autocomplete="off" checked> <label class="btn btn-outline-success" for="Kitchen_blinds_Open">Open</label> <input type="radio" class="btn-check" name="Kitchen_blinds" id="Kitchen_blinds_Closed" autocomplete="off"> <label class="btn btn-outline-danger" for="Kitchen_blinds_Closed">Close</label> </div> </div> </div> '
});
$("#bedroom_ac").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Master Bedroom AC </div> <div class="card-body"> <select class="form-select" aria-label="MasterBedroomAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#office_ac").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Home Office </div> <div class="card-body"> <select class="form-select" aria-label="HomeOfficeAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#kitchen_ac").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen AC </div> <div class="card-body"> <select class="form-select" aria-label="KitchenAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#bathroom_ac").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Bathroom AC </div> <div class="card-body"> <select class="form-select" aria-label="BathroomAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#kitchen_camera_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen </div> <div class="card-body"> place for video camera </div> </div>'
});
$("#kitchen_ac_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen AC </div> <div class="card-body"> <select class="form-select" aria-label="KitchenAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#kitchen_blinds_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Kitchen Blinds </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Kitchen_blinds2"> <input type="radio" class="btn-check" name="Kitchen_blinds2" id="Kitchen_blinds2_Open"autocomplete="off" checked> <label class="btn btn-outline-success" for="Kitchen_blinds2_Open">Open</label> <input type="radio" class="btn-check" name="Kitchen_blinds2" id="Kitchen_blinds2_Closed" autocomplete="off"> <label class="btn btn-outline-danger" for="Kitchen_blinds2_Closed">Close</label> </div> </div> </div>'
});
$("#kitchen_sink_2").append(function(){
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Kitchen Sink </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="KitchenSink2"> <input type="radio" class="btn-check" name="KitchenSink2" id="KitchenSink2_ON"  autocomplete="off"> <label class="btn btn-outline-success" for="KitchenSink2_ON">ON</label> <input type="radio" class="btn-check" name="KitchenSink2" id="KitchenSink2_OFF" autocomplete="off" checked> <label class="btn btn-outline-danger" for="KitchenSink2_OFF">OFF</label> </div> <select class="form-select" aria-label="KitchenSink"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#kitchen_light_11").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Kitchen Main Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Kitchen_Main_Light"> <input type="radio" class="btn-check" name="Kitchen_Main_Light" id="Kitchen_Main_Light_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Kitchen_Main_Light_ON">ON</label> <input type="radio" class="btn-check" name="Kitchen_Main_Light" id="Kitchen_Main_Light_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Kitchen_Main_Light_OFF">OFF</label> </div> </div> </div>'
  });
$("#kitchen_light_22").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Kitchen Ambient Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Kitchen_Ambient_Light"> <input type="radio" class="btn-check" name="Kitchen_Ambient_Light" id="Kitchen_Ambient_Light_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Kitchen_Ambient_Light_ON">ON</label> <input type="radio" class="btn-check" name="Kitchen_Ambient_Light" id="Kitchen_Ambient_Light_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Kitchen_Ambient_Light_OFF">OFF</label> </div> </div> </div>'
  });
$("#bathroom_ac_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> AC </div> <div class="card-body"> <select class="form-select" aria-label="BathroomAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });
$("#bathroom_shower_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Shower </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Shower2_ON"> <input type="radio" class="btn-check" name="Shower2_ON" id="Shower2_on"  autocomplete="off"> <label class="btn btn-outline-success" for="Shower2_on">ON</label> <input type="radio" class="btn-check" name="Shower2_ON" id="Shower2_off" autocomplete="off" checked> <label class="btn btn-outline-danger" for="Shower2_off">OFF</label> </div> <select class="form-select" aria-label="Shower"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });
$("#bathroom_sink_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Sink </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="BathroomSink2"> <input type="radio" class="btn-check" name="BathroomSink2" id="BathroomSink2_ON"  autocomplete="off"> <label class="btn btn-outline-success" for="BathroomSink2_ON">ON</label> <input type="radio" class="btn-check" name="BathroomSink2" id="BathroomSink_OFF" autocomplete="off" checked> <label class="btn btn-outline-danger" for="BathroomSink2_OFF">OFF</label> </div> <select class="form-select" aria-label="BathroomSink2"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
});
$("#bathroom_light_2").append(function () {
      return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="BathroomLight2"> <input type="radio" class="btn-check" name="BathroomLight2" id="BathroomLight2_ON"  autocomplete="off"> <label class="btn btn-outline-success" for="BathroomLight2_ON">ON</label> <input type="radio" class="btn-check" name="BathroomLight2" id="BathroomLight2_OFF" autocomplete="off" checked> <label class="btn btn-outline-danger" for="BathroomLight2_OFF">OFF</label> </div> </div> </div>'
});
$("#front_lock_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Front door </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Front_door_Lock"> <input type="radio" class="btn-check" name="Front_door_Lock" id="Front_door_lock"  autocomplete="off" checked> <label class="btn btn-outline-success" for="Front_door_lock">Lock</label> <input type="radio" class="btn-check" name="Front_door_Lock" id="Front_door_unLock" autocomplete="off"> <label class="btn btn-outline-danger" for="Front_door_unLock">Unlock</label> </div> </div> </div>'
});
$("#corridor_light_11").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Corridor Main Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Corridor_light_main"> <input type="radio" class="btn-check" name="Corridor_light_main" id="Corridor_light_main_on"  autocomplete="off" checked> <label class="btn btn-outline-success" for="Corridor_light_main_on">ON</label> <input type="radio" class="btn-check" name="Corridor_light_main" id="Corridor_light_main_off" autocomplete="off"> <label class="btn btn-outline-danger" for="Corridor_light_main_off">OFF</label> </div> </div> </div>'
  });
$("#corridor_light_22").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Corridor Ambient Light </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Corridor_light_Ambient"> <input type="radio" class="btn-check" name="Corridor_light_Ambient" id="Corridor_light_Ambient_on"  autocomplete="off" checked> <label class="btn btn-outline-success" for="Corridor_light_Ambient_on">ON</label> <input type="radio" class="btn-check" name="Corridor_light_Ambient" id="Corridor_light_Ambient_off" autocomplete="off"> <label class="btn btn-outline-danger" for="Corridor_light_Ambient_off">OFF</label> </div> </div> </div>'
  });
$("#corridor_camera_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Corridor camera </div> <div class="card-body"> Place for the camera </div> </div>'
  });
$("#bedroom_lock_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Lock </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Bedroom_Lock"> <input type="radio" class="btn-check" name="Bedroom_Lock" id="M_Bedroom_Lock2" autocomplete="off" checked> <label class="btn btn-outline-success" for="M_Bedroom_Lock2">Lock</label> <input type="radio" class="btn-check" name="Bedroom_Lock" id="M_Bedroom_unLock2" autocomplete="off"> <label class="btn btn-outline-danger" for="M_Bedroom_unLock2">Unlock</label> </div> </div> </div>'
  });
$("#bedroom_camera_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Camera </div> <div class="card-body"> place for video camera </div> </div>'
  });
$("#bedroom_ac_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> AC </div> <div class="card-body"> <select class="form-select" aria-label="MasterBedroomAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });
$("#bedroom_blinds_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Blinds </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Bedroom_Window2_blinds"> <input type="radio" class="btn-check" name="Bedroom_Window2_blinds" id="Master_blinds2_Open"autocomplete="off" checked> <label class="btn btn-outline-success" for="Master_blinds_Open">Open</label> <input type="radio" class="btn-check" name="Bedroom_Window2_blinds" id="Master_blinds2_Closed" autocomplete="off"> <label class="btn btn-outline-danger" for="Master_blinds2_Closed">Close</label> </div> </div> </div>'
  });
$("#bedroom_light_11").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Main Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Bedroom_Main_Light2"> <input type="radio" class="btn-check" name="Bedroom_Main_Light2" id="Master_Bedroom_Main_Light2_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Master_Bedroom_Main_Light2_ON">ON</label> <input type="radio" class="btn-check" name="Bedroom_Main_Light2" id="Master_Bedroom_Main_Light2_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Master_Bedroom_Main_Light2_OFF">OFF</label> </div> </div> </div>  '
  });
$("#bedroom_light_22").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Ambient Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Bedroom_Ambient_Light2"> <input type="radio" class="btn-check" name="Bedroom_Ambient_Light2" id="Master_Bedroom_Ambient_Light2_ON"autocomplete="off" checked> <label class="btn btn-outline-success" for="Master_Bedroom_Ambient_Light2_ON">ON</label> <input type="radio" class="btn-check" name="Bedroom_Ambient_Light2" id="Master_Bedroom_Ambient_Light2_OFF" autocomplete="off"> <label class="btn btn-outline-danger" for="Master_Bedroom_Ambient_Light2_OFF">OFF</label> </div> </div> </div>'
  });
$("#office_camera_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Home Office </div> <div class="card-body"> place for video camera </div> </div>'
  });
$("#office_ac_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <div class="card-header"> Home Office </div> <div class="card-body"> <select class="form-select" aria-label="HomeOfficeAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });
$("#office_blinds_2").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Office Blinds </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="Office_blinds2"> <input type="radio" class="btn-check" name="Office_blinds2" id="Office_blinds2_Open"autocomplete="off" checked> <label class="btn btn-outline-success" for="Office_blinds2_Open">Open</label> <input type="radio" class="btn-check" name="Office_blinds2" id="Office_blinds2_Closed" autocomplete="off"> <label class="btn btn-outline-danger" for="Office_blinds2_Closed">Close</label> </div> </div> </div>'
  });
$("#office_light_11").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Main Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="office_Main_Light"> <input type="radio" class="btn-check" name="office_Main_Light" id="office_Main_Light_on"autocomplete="off" checked> <label class="btn btn-outline-success" for="office_Main_Light_on">ON</label> <input type="radio" class="btn-check" name="office_Main_Light" id="office_Main_Light_on" autocomplete="off"> <label class="btn btn-outline-danger" for="office_Main_Light_on">OFF</label> </div> </div> </div>'
  });
$("#office_light_22").append(function () {
    return '<div class="card card_element col-5 col-lg-3"> <card class="card-header"> Ambient Light </card> <div class="card-body"> <div class="btn-group" role="group" aria-label="office_Ambient_Light"> <input type="radio" class="btn-check" name="office_Ambient_Light" id="office_Ambient_Light_on"autocomplete="off" checked> <label class="btn btn-outline-success" for="office_Ambient_Light_on">ON</label> <input type="radio" class="btn-check" name="office_Main_Light" id="office_Ambient_Light_off" autocomplete="off"> <label class="btn btn-outline-danger" for="office_Ambient_Light_off">OFF</label> </div> </div> </div>'
  });
$("#bathroom_shower").append(function () {
    return '<div class="card card_element"> <div class="card-header"> Shower </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="Shower_ON"> <input type="radio" class="btn-check" name="Shower_ON" id="Shower_on"  autocomplete="off"> <label class="btn btn-outline-success" for="Shower_on">ON</label> <input type="radio" class="btn-check" name="Shower_ON" id="Shower_off" autocomplete="off" checked> <label class="btn btn-outline-danger" for="Shower_off">OFF</label> </div> <select class="form-select" aria-label="ShowerAC"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });
$("#bathroom_sink").append(function () {
    return '<div class="card card_element"> <div class="card-header"> Bathroom Sink </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="BathroomSink"> <input type="radio" class="btn-check" name="BathroomSink" id="BathroomSink_ON"  autocomplete="off"> <label class="btn btn-outline-success" for="BathroomSink_ON">ON</label> <input type="radio" class="btn-check" name="BathroomSink" id="BathroomSink_OFF" autocomplete="off" checked> <label class="btn btn-outline-danger" for="BathroomSink_OFF">OFF</label> </div> <select class="form-select" aria-label="BathroomSink"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });
$("#kitchen_sink").append(function () {
    return '<div class="card card_element"> <div class="card-header"> Kitchen Sink </div> <div class="card-body"> <div class="btn-group" role="group" aria-label="KitchenSink"> <input type="radio" class="btn-check" name="KitchenSink" id="KitchenSink_ON"  autocomplete="off"> <label class="btn btn-outline-success" for="KitchenSink_ON">ON</label> <input type="radio" class="btn-check" name="KitchenSink" id="KitchenSink_OFF" autocomplete="off" checked> <label class="btn btn-outline-danger" for="KitchenSink_OFF">OFF</label> </div> <select class="form-select" aria-label="BathroomSink"> <option selected>Select the temperature</option> <option value="15">15 &#8451</option> <option value="16">16 &#8451</option> <option value="17">17 &#8451</option> <option value="18">18 &#8451</option> <option value="19">19 &#8451</option> <option value="20">20 &#8451</option> <option value="21">21 &#8451</option> <option value="22">22 &#8451</option> <option value="23">23 &#8451</option> <option value="24">24 &#8451</option> <option value="25">25 &#8451</option> <option value="26">26 &#8451</option> <option value="27">27 &#8451</option> <option value="28">28 &#8451</option> </select> </div> </div>'
  });                        